### ISSUE TITLE
GET request for user_timeline returns 401 error

### ISSUE THREAD

**Issue by zakdances** [sreejithbnaick/Twitter-OAuth-1.1-Signature-Generator-js#8]
I'm trying to return a user timeline for a specific screen_name and all I'm getting back is 401 errors. The Cloud Code I'm using in my main.js:

```
Parse.Cloud.define("twitterTimeline", function(request, response) {
    var screen_name = "myscreenname";
    var urlLink = 'https://api.twitter.com/1.1/statuses/user_timeline.json';

    var consumerSecret = "myconsumersecret";
    var tokenSecret = "mytokensecret";
    var oauth_consumer_key = "myoauthkey";
    var oauth_token = "myoauthtoken";

    var nonce = oauth.nonce(32);
    var ts = Math.floor(new Date().getTime() / 1000);
    var timestamp = ts.toString();

    var accessor = {
        "consumerSecret": consumerSecret,
        "tokenSecret": tokenSecret
    };


    var params = {
        "oauth_version": "1.0",
        "oauth_consumer_key": oauth_consumer_key,
        "oauth_token": oauth_token,
        "oauth_timestamp": timestamp,
        "oauth_nonce": nonce,
        "oauth_signature_method": "HMAC-SHA1",
        "screen_name": screen_name,
        "count": 5,
        "include_rts": 1
    };
    var message = {
        "method": "GET",
        "action": urlLink,
        "parameters": params
    };


    //lets create signature
    oauth.SignatureMethod.sign(message, accessor);
    var normPar = oauth.SignatureMethod.normalizeParameters(message.parameters);
    console.log("Normalized Parameters: " + normPar);
    var baseString = oauth.SignatureMethod.getBaseString(message);
    console.log("BaseString: " + baseString);
    var sig = oauth.getParameter(message.parameters, "oauth_signature") + "=";
    console.log("Non-Encode Signature: " + sig);
    var encodedSig = oauth.percentEncode(sig); //finally you got oauth signature
    console.log("Encoded Signature: " + encodedSig);

    Parse.Cloud.httpRequest({
        method: 'GET',
        url: urlLink,
        headers: {
            "Authorization": 'OAuth oauth_consumer_key="'+oauth_consumer_key+'", oauth_nonce=' + nonce + ', oauth_signature=' + encodedSig + ', oauth_signature_method="HMAC-SHA1", oauth_timestamp=' + timestamp + ',oauth_token="'+oauth_token+'", oauth_version="1.0"'
        },
        body: {
        },
        success: function(httpResponse) {
            response.success(httpResponse.text);
        },
        error: function(httpResponse) {
            response.error('Request failed with response ' + httpResponse.status + ' , ' + httpResponse);
        }
    });
});

```

Why is this failing?

**Comment by sreejithbnaick** [comment]
@zakdances Sorry for late response. Its because I'm not maintaing this code.
I know whats wrong with your code. Instead of putting  "screen_name" & "count" in params, tag it along "urlLink"

for eg: var urlLink = 'https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=name&count=2';

**Comment by ummarahashraf** [comment]
hi can u help me with this code mm getting errors
Parse.Cloud.define("twitterTimeline", function(request, response) {
    var screen_name = "UmmarahAshraf";
    var urlLink = 'https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=UmmarahAshraf';

    var consumerSecret = "x3D8jRaANkD7LoArBAJrWogzwUZQTOenAs3lffvN0XoYTxrRPK";
    var tokenSecret = "SJnylMHk4DE1WBZqQdyxVZaMpqnVBSHkQwYJLdUQY1kWZ";
    var oauth_consumer_key = "3M8nTnqgCAriugAmtAfF9AnkE";
    var oauth_token = "899890372423417856-tUPXQF19fxSRcNuh9UOOU6A5Fg1MDKl";

    var nonce = oauth.nonce(32);
    var ts = Math.floor(new Date().getTime() / 1000);
    var timestamp = ts.toString();

    var accessor = {
        "consumerSecret": consumerSecret,
        "tokenSecret": tokenSecret
    };


    var params = {
        "oauth_version": "1.0",
        "oauth_consumer_key": oauth_consumer_key,
        "oauth_token": oauth_token,
        "oauth_timestamp": timestamp,
        "oauth_nonce": nonce,
        "oauth_signature_method": "HMAC-SHA1",
        "screen_name": screen_name,
        "count": 5,
        "include_rts": 1
    };
    var message = {
        "method": "GET",
        "action": urlLink,
        "parameters": params
    };


    //lets create signature
    oauth.SignatureMethod.sign(message, accessor);
    var normPar = oauth.SignatureMethod.normalizeParameters(message.parameters);
    console.log("Normalized Parameters: " + normPar);
    var baseString = oauth.SignatureMethod.getBaseString(message);
    console.log("BaseString: " + baseString);
    var sig = oauth.getParameter(message.parameters, "oauth_signature") + "=";
    console.log("Non-Encode Signature: " + sig);
    var encodedSig = oauth.percentEncode(sig); //finally you got oauth signature
    console.log("Encoded Signature: " + encodedSig);

    Parse.Cloud.httpRequest({
        method: 'GET',
        url: urlLink,
        headers: {
            "Authorization": 'OAuth oauth_consumer_key="'+oauth_consumer_key+'", oauth_nonce=' + nonce + ', oauth_signature=' + encodedSig + ', oauth_signature_method="HMAC-SHA1", oauth_timestamp=' + timestamp + ',oauth_token="'+oauth_token+'", oauth_version="1.0"'
        },
        body: {
        },
        success: function(httpResponse) {
            response.success(httpResponse.text);
        },
        error: function(httpResponse) {
            response.error('Request failed with response ' + httpResponse.status + ' , ' + httpResponse);
        }
    });
});
