### ISSUE TITLE
Request failed with response 401

### ISSUE THREAD

**Issue by thellimist** [sreejithbnaick/Twitter-OAuth-1.1-Signature-Generator-js#9]
I'm not sure if the problem is caused by the library or app settings but I'm getting this error. My keys seem to be correct. I'm trying to get home_timeline. Also Application settings access level is - Read, write, and direct messages. 

Help would be appreciated.

**Comment by sreejithbnaick** [comment]
Did you try the sample code from README?

**Comment by thellimist** [comment]
Yes I did. The exact same code with correct keys doesn't seem to work. I recreated the keys and tried again, nothing changed.

**Comment by thellimist** [comment]
The reason was the way I was querying. Instead of q=? q=%3F solved the problem. The library works fine thank you.
